roombooking/book/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'book'
urlpatterns = [
    path('new/slot', slot, name="slot"),
    path('',home,name="home"),
    path('new/booking',book,name="book"),
    path('<int:id>', views.cancle,name='cancle'),
    path('edit/<int:id>',views.edit),
    path('edit/slots',views.desc),
    path('edit/slot/<int:id>',views.edits),
    path('ajax',views.ajax),
    path('ajax/slot',views.ajaxs),
    path('cancle/<int:id>',views.cancles),
    path('api',views.slot_api),
    path('new/room',views.add_room),
    path('change',views.change_days),
]

roombooking/roombooking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('login.urls')),
    path('book/', include('book.urls')),
]

roombooking/book/models.py
from django.db import models
from login.models import User
# Create your models here.

class Room(models.Model):
    name=models.CharField(max_length=24)
    def __str__(self):
        return self.name

class Time_slots(models.Model):
    int_time=models.TimeField()
    end_time=models.TimeField()

class Bookings(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    slot_id=models.ForeignKey(Time_slots,on_delete=models.CASCADE)
    date=models.DateField(null=True,default=None)
    room=models.ForeignKey(Room,on_delete=models.CASCADE,null=True,default=None)

class dependent(models.Model):
    date=models.DateField()
    time_slot=models.ForeignKey(Time_slots,on_delete=models.CASCADE)

class advance(models.Model):
    no_days=models.IntegerField()
    

roombooking/book/forms.py
from django import forms
from .models import *

class time_slot_form(forms.Form):
    ini_time=forms.TimeField()
    end_time=forms.TimeField()


class bookings_form(forms.Form):
    MY_CHOICES=()
    x=Time_slots.objects.all()
    for i in x:
        MY_CHOICES += ((i.pk, str(i.int_time)+' -- '+str(i.end_time)),)
    date=forms.DateField()
    time_slot=forms.ChoiceField(choices=MY_CHOICES)


class room_form(forms.Form):
    name=forms.CharField(max_length=25)


class max_d(forms.Form):
    days=forms.IntegerField()

roombooking/book/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import *
from .models import *
from django.contrib import messages
from django.shortcuts import redirect
import datetime
from datetime import date
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt


def slot(request):
    if not request.user.is_manager:
        return HttpResponse('<h1>Customer</h1>')
    else:
        if request.method=="POST":
            form=time_slot_form(request.POST)
            if form.is_valid():
                ini_time=form.cleaned_data["ini_time"]
                end_time=form.cleaned_data["end_time"]
                obj=Time_slots.objects.create(int_time=ini_time,end_time=end_time)
                obj.save()
                messages.success(request, "Slot successfully added")
                return redirect('/book/')
            else:
                messages.MessageFailure(request, 'Not created')  
        form=time_slot_form()
        x=datetime.datetime.now().date()+datetime.timedelta(days=advance.objects.get(pk=1).no_days)
        context={'form':form,'x':x}
        return render(request,'book/slot_form.html',context)

def date(i):
    return i.date

def home(request):
    if not request.user.is_manager:
        booking1=Bookings.objects.all()
        booking1=sorted(booking1,key=date,reverse=True)
        for i in booking1:
            print(i.date)
        booking=[]
        for i in booking1:
            if i.user==request.user:
                booking.append(i)
        a=[]
        b=""
        for x in booking:
            b=b+str(x.room.name)+"  "
            b=b+str((x.date.strftime('%A %d %B %Y')))+"  "
            b=b+str(x.slot_id.int_time)
            b=b+"  To  "+str(x.slot_id.end_time)
            a.append((b,x.pk,bool(datetime.datetime.combine(x.date,x.slot_id.int_time)>datetime.datetime.now())))
            b=""
        print(a)
        contex={'a':a}
        return render(request,'book/home.html',contex)
    else:
        date1=datetime.datetime.now().date()
        x=Bookings.objects.filter(date=date1)
        a=[]
        b={}
        c=[]
        for i in x:   
            b["roomname"]=str(i.room.name)
            b["status"]="Booked"
            b["intt"]=str(i.slot_id.int_time)
            b["endt"]=str(i.slot_id.end_time)
            b["user"]=str(i.user)
            a.append(b)
            b={}
        for i in Room.objects.all():
            if i not in [z.room for z in x]:
                b["roomname"]=str(i.name)
                b["status"]="Vaccant"
                c.append(b)
                b={}
        context={'a':a,'c':c,'date1':date1}
        return render(request,'book/m_home.html',context)


def book(request):
    if not request.user.is_manager:
        if request.method=="POST":
            form=bookings_form(request.POST)
            if form.is_valid():
                date=form.cleaned_data["date"]
                time_slot=Time_slots.objects.get(pk=form.cleaned_data["time_slot"])
                booking=[i.room for i in Bookings.objects.filter(date=date).filter(slot_id=time_slot)]
                for i in Room.objects.all():
                    if i not in booking:
                        break
                obj=Bookings.objects.create(user=request.user,date=date,slot_id=time_slot,room=i)
                obj.save()
                messages.success(request, "Slot successfully added")
                return redirect('/book/')
            else:
                print(form)
                messages.MessageFailure(request, 'Not created') 
        form=bookings_form()
        context={'form':form,'max':advance.objects.get(pk=1).no_days}
        return render(request,'book/book_form.html',context)
    else:
        return HttpResponse('<h1>Manager</h1>')

def edit(request,id):
    if not request.user.is_manager:
        if request.method=="POST":
           form=bookings_form(request.POST)
           print("hi")
           if form.is_valid():
                print("hi")
                date=form.cleaned_data["date"]
                time_slot=Time_slots.objects.get(pk=form.cleaned_data["time_slot"])
                booking=[i.room for i in Bookings.objects.filter(date=date).filter(slot_id=time_slot)]
                Bookings.objects.get(pk=id).delete()
                for i in Room.objects.all():
                    if i not in booking:
                        break
                obj=Bookings.objects.create(user=request.user,date=date,slot_id=time_slot,room=i)
                obj.save()
                messages.success(request, "Slot successfully added")
                return redirect('/book/')
        booking=Bookings.objects.get(pk=id)
        print(booking.slot_id.pk)
        form=bookings_form(initial={'time_slot':booking.slot_id.pk,'date':booking.date})
        contest={'form':form}
        return render(request,'book/book_form.html',contest)
        
def cancle(request,id):
    if not request.user.is_manager:
        boooking=Bookings.objects.get(pk=id)
        boooking.delete()
        return redirect('/book/')
    else:
        return HttpResponse('<h1>Manager</h1>')

def ajax(request):
    print("Hi")
    date=request.GET.get('date')
    x=Bookings.objects.filter(date=date)
    a=[]
    b=[]
    for i in x:   
        b.append(str(i.room.name))
        b.append("Booked")
        b.append(str(i.slot_id.int_time))
        b.append(str(i.slot_id.end_time))
        b.append(str(i.user))
        a.append(b)
        b=[]
    for i in Room.objects.all():
        if i not in [z.room for z in x]:
            b.append(str(i.name))
            b.append("Vaccant")
            for y in range(3):
                b.append("NA")
            a.append(b)
            b=[]
    context={'a':a}
    return JsonResponse(context)

def desc(request):
    if request.user.is_manager:
        dep=dependent.objects.all()
        for i in range(len(dep)):
            if datetime.datetime.now().date()<(dep[i].date):
                break
        x=dependent.objects.filter(date=dep[max(i-1,0)].date)
        time=[]
        for i in x:
            time.append(i.time_slot)
        x=datetime.datetime.now().date()+datetime.timedelta(days=advance.objects.get(pk=1).no_days)
        y=1
        if datetime.datetime.now().date() in [z.date for z in dep]:
            y=0
        context={'time':time,'date1':datetime.datetime.now().date(),'date2':x,'y':y}
        return render(request,'book/time_slot.html',context)

def edits(request,id):
    if request.user.is_manager:
        if request.method=="POST":
            form=time_slot_form(request.POST)
            if form.is_valid():
                ini_time=form.cleaned_data["ini_time"]
                end_time=form.cleaned_data["end_time"]
                obj=Time_slots.objects.create(int_time=ini_time,end_time=end_time)
                obj.save()
                x=datetime.datetime.now().date()+datetime.timedelta(days=advance.objects.get(pk=1).no_days)
                for i in Time_slots.objects.all():
                    if not i.pk==id:
                        dependent.objects.create(date=x,time_slot=i).save()
                messages.success(request, "Slot successfully added")
                return redirect('/book/edit/slots')
        slot=Time_slots.objects.get(pk=id)
        x=datetime.datetime.now().date()+datetime.timedelta(days=advance.objects.get(pk=1).no_days)
        print(x)
        form=time_slot_form()
        context={'form':form,'x':x,'in':slot.int_time,'out':slot.end_time}
        return render(request,'book/slot_form.html',context)
        
def cancles(request,id):
    x1=datetime.datetime.now().date()+datetime.timedelta(days=advance.objects.get(pk=1).no_days)
    dep=dependent.objects.all()
    for i in range(len(dep)):
        if datetime.datetime.now().date()<(dep[i].date):
            break
    y=dependent.objects.filter(date=dep[max(i-1,0)].date)
    for i in y:
        if not i.time_slot.pk==id:
            dependent.objects.create(date=x1,time_slot=i.time_slot).save()
    return redirect('/book/edit/slots')

def ajaxs(request):
    date=request.GET.get('date')
    print(date)
    dep=dependent.objects.all()
    print(dep[0].date)
    for i in range(len(dep)):
        if str(date)<str(dep[i].date):
            break
    x=dependent.objects.filter(date=dep[max(i-1,0)].date)
    a=[]
    b=[]
    for i in x:
        b.append(i.time_slot.int_time)
        b.append(i.time_slot.end_time)
        b.append(i.time_slot.pk)
        a.append(b)
        b=[]
    print(a)
    context={'a':a}
    return JsonResponse(context)

def add_room(request):
    if request.user.is_manager:
        if request.method=="POST":
            form=room_form(request.POST)
            if form.is_valid():
                name=form.cleaned_data["name"]
                Room.objects.create(name=name).save()
                return redirect('/book/')
        form=room_form()
        contex={'form':form}
        return render(request,'book/add_room.html',contex)
    else:
        return HttpResponse('<h1>Customer</h1>')

def change_days(request):
    if request.user.is_manager:
        if request.method=="POST":
            form=max_d(request.POST)
            if form.is_valid():
                days=form.cleaned_data["days"]
                obj=advance.objects.get(pk=1)
                obj.no_days=days
                obj.save()
                return redirect('/book/')
        form=max_d()
        contex={'form':form,'days':advance.objects.get(pk=1).no_days}
        return render(request,'book/change_days.html',contex)
    else:
        return HttpResponse('<h1>Customer</h1>')


@csrf_exempt 
def slot_api(request):
    if request.method=="POST":
        print(request.body)
        data=request.body.decode('utf-8')
        received_json_data = json.loads(data)
        time1=received_json_data["int_time"]
        time2=received_json_data["end_time"]

roombooking/book/templates/book/add_room.html
{% load static %}
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="{% static 'login/signup.css' %}">
</head>
<body>
  <form method="post" style="border:1px solid #ccc">
      {% csrf_token %}
    <div class="container">
      <h1>Room Creation Form</h1>
      <label for="id_name">Name:</label>&nbsp;&nbsp;
      <input type="text" name="name" required maxlength="25" id="id_name">
      <div class="clearfix">
        <button type="submit" class="signupbtn">Create</button>
      </div>
    </div>
  </form>
</body>

roombooking/book/templates/book/book_form.html
{% load static %}
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" type="text/css" href="{% static 'login/signup.css' %}">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $( function() {
        $( "#id_date" ).datepicker({ dateFormat: 'yy-mm-dd', minDate: 0, maxDate: "{{ max }}" });
        } );
        $(document).on("change", "#id_date", function () {
        date=this.value;
        $.ajax({
            url: '/book/ajax/slot',
            type: 'GET',
            dataType: 'json',
            data: {date: date},
            success: function(response)
            {
                var a=response["a"];
                console.log(a);
                var q=a.length;
                console.log(q);
                z=document.getElementById("id_time_slot");
                console.log(z.innerHTML);
                var y="";
                for(var i=0; i< a.length; i++)
                { 
                    y+="<option value=\""+a[i][2]+"\">"+a[i][0]+" -- "+a[i][1]+"</option>";
                }
                z.innerHTML=y;
            }
        });
    });
    </script>
  </head>
<form method="post">
    {% csrf_token %}
    <div class="container">
        <h1>Booking Form</h1>
        <label for="id_date" style="font-size: 25px; height: 150px;">Date:</label>
        <input type="text" name="date" required id="id_date" style="width: 40%;" placeholder="yy:mm:ss">
        <br>
        <br>
        {{ form.time_slot }}
        <br><br>
    <div class="clearfix">
        <button type="submit" class="signupbtn">Create</button>
    </div>
    </div>
</form>

roombooking/book/templates/book/change_days.html
{% load static %}
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="{% static 'login/signup.css' %}">
</head>
<body>
  <form method="post" style="border:1px solid #ccc">
      {% csrf_token %}
    <div class="container">
      <h1>Room Creation Form</h1>
      <br>
      <label for="id_days">Days:</label>&nbsp;&nbsp;
      <input type="number" name="days" required id="id_days" style="width: 300px; height: 30px;" value="{{ days }}">
      <br><br>
      <div class="clearfix">
        <button type="submit" class="signupbtn">Create</button>
      </div>
    </div>
  </form>
</body>

roombooking/book/templates/book/home.html
<!DOCTYPE html>
{% load static %}
{% load nbsp %}
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'book/home.css' %}">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>
<div class="w3-sidebar w3-light-grey w3-bar-block" style="width:25%">
  <h3 class="w3-bar-item">Menu</h3>
  <a href="/book/new/booking" class="w3-bar-item w3-button">Create new booking</a>
  <a href="/user/logout" class="w3-bar-item w3-button">Logout</a>
</div>
<div style="margin-left:25%">

    <div class="w3-container w3-teal">
    <h1>Your Bookings</h1>
    </div>


    <div class="w3-container">
        {% for x in a %} 
                <div class="horizontal" style="margin-right: 16px">  
                    <li> 
                        {{ x.0|nbsp }}
                        {% if x.2 %}
                            <a href="/book/edit/{{ x.1 }}"><button class="btn edit" style="margin-left: 25px">Edit</button></a>
                            <a href="/book/{{ x.1 }}" onclick="return confirm('Are you sure you want to Remove?');"><button class="btn delete" style="margin-left: 25px">Delete</button></a>
                        {% endif %}
                    </li>    
                </div>
        {% endfor %}
    </div>
</div>     
</body>
</html>

roombooking/book/templates/book/m_home.html
{% load static %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'book/man.css' %}">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $( function() {
    $( "#id_date" ).datepicker({ dateFormat: 'yy-mm-dd' });
    } );
    console.log("Hi");
    $(document).on("change", "#id_date", function () {
        date=this.value;
        $.ajax({
            url: '/book/ajax',
            type: 'GET',
            dataType: 'json',
            data: {date: date},
            success: function(response){
                var a=response["a"];
                console.log(a);
                console.log(a.length);
                var y = document.getElementById("myTable").rows.length;
                z=document.getElementById("myTable");
                for(var i=0;i<a.length && i<y-1;i++)
                {
                    var x = z.rows[i+1].cells;
                    for(var j=0;j<5;j++)
                    {
                        x[j].innerHTML=a[i][j]
                    }
                }
                for(i=y-1;i<a.length;i++)
                {
                    var y="<tr><td>";
                    for(var k=0;k<4;k++)
                    {
                        y=y+a[i][k]+"</td><td>";
                    }
                    y=y+a[i][k]+"</td></tr>";
                    z.innerHTML+=y;
                }
                for(i=a.length+1;i<y;i++)
                {
                    console.log(y-i);
                    z.deleteRow(a.length+1);
                }
            }
        });
    });
</script>
</head>
<div class="sidenav">
    <a href="/book/">Home</a>
    <a href="/book/new/room">Add Room</a>
    <a href="/book/new/slot">Create new time slot</a>
    <a href="/book/edit/slots">Edit Time slots</a>
    <a href="/book/change">Days for advance booking</a>
    <a href="/user/logout">Logout</a>
</div>
{% csrf_token %}
<div class="main">
    <h1>Status</h1>
    <div id="element2">
        <label for="id_date">Choose date:</label>
        <input type="text" id="id_date" class="date" value="{{ date1 }}">
    </div>
    <br>
    <br>
    <table style="width:100%" id="myTable">
        <tr>
            <th>Roomname</th>
            <th>Status</th>
            <th>Start time</th> 
            <th>End time</th>
            <th>User</th>
        </tr>
        {% for i in a %}
            <tr>
                <td>{{ i.roomname }}</td>
                <td>{{ i.status }}</td>
                <td>{{ i.intt }}</td>
                <td>{{ i.endt }}</td>
                <td>{{ i.user }}</td>
            </tr>
        {% endfor %}
        {% for i in c %}
            <tr>
                <td>{{ i.roomname }}</td>
                <td>{{ i.status }}</td>
                <td>NA</td>
                <td>NA</td>
                <td>NA</td>
            </tr>
        {% endfor %}
    </table>
</div>
</html> 

roombooking/book/templates/book/slot_form.html
{% load static %}
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="{% static 'login/signup.css' %}">
</head>
<body>
  <form method="post" style="border:1px solid #ccc">
      {% csrf_token %}
    <div class="container">
      <h1>Slot Creation Form</h1>
  <p><b>Please Note</b>: The following changes will be applied form {{ x }}</p>
      <label for="id_ini_time">Start time:</label>
      <input type="text" name="ini_time" id="id_ini_time" value="{{ in|time:"H:i:s" }}" placeholder="hh:mm:ss" required>
      <label for="id_end_time">End time:</label>
      <input type="text" name="end_time" id="id_end_time" value="{{ out|time:"H:i:s" }}" placeholder="hh:mm:ss" required>
      <div class="clearfix">
        <button type="submit" class="signupbtn">Create</button>
      </div>
    </div>
  </form>
</body>

roombooking/book/templates/book/time_slot.html
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'book/man.css' %}">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
    $( function() {
    $( "#id_date" ).datepicker({ dateFormat: 'yy-mm-dd' });
    } );
</script>
<style>
    table{
    font-family:'Calibri';
    font-size:15px;
    background-color:#fff;
    color:#333;
}
</style>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script>
    $(document).on("change", "#id_date", function () {
        date=this.value;
        $.ajax({
            url: '/book/ajax/slot',
            type: 'GET',
            dataType: 'json',
            data: {date: date},
            success: function(response){
                var a=response["a"];
                console.log(a);
                console.log(a.length);
                var y = document.getElementById("myTable").rows.length;
                console.log("Y is "+y);
                z=document.getElementById("myTable");
                for(var i=1;i<=a.length && i<y;i++)
                {
                    var x = z.rows[i].cells;
                    console.log(x[0].innerHTML);
                    x[0].innerHTML=a[i-1][0];
                    x[1].innerHTML=a[i-1][1];
                    x[2].innerHTML="<td><button type=\"button\" data-toggle=\"modal\" data-target=\"#edit\" data-uid=\"1\" class=\"update btn btn-warning btn-sm\"><span class=\"glyphicon glyphicon-pencil\"></span></button>";
                    x[3].innerHTML="</td></a><td><button type=\"button\" data-toggle=\"modal\" data-target=\"#delete\" data-uid=\"1\" class=\"delete btn btn-danger btn-sm\"><span class=\"glyphicon glyphicon-trash\"></span></button></td>";
                }
                for(i=a.length+1;i<y;i++)
                {
                    console.log(i)
                    z.deleteRow(a.length+1);
                }
                for(i=y-1;i<a.length;i++)
                {
                    var y="<tr><td>";
                    y=y+a[i][0]+"</td><td>";
                    y=y+a[i][1]+"</td>";
                    y=y+"<td><button type=\"button\" data-toggle=\"modal\" data-target=\"#edit\" data-uid=\"1\" class=\"update btn btn-warning btn-sm\"><span class=\"glyphicon glyphicon-pencil\"></span></button></td></a><td><button type=\"button\" data-toggle=\"modal\" data-target=\"#delete\" data-uid=\"1\" class=\"delete btn btn-danger btn-sm\"><span class=\"glyphicon glyphicon-trash\"></span></button></td>";
                    z.innerHTML+=y;
                }
                console.log(z.innerHTML);
            }
        });
    });
</script>
<div class="sidenav">
    <a href="/book/">Home</a>
    <a href="/book/new/room">Add Room</a>
    <a href="/book/new/slot">Create new time slot</a>
    <a href="/book/edit/slots">Edit Time slots</a>
    <a href="/book/change">Days for advance booking</a>
    <a href="/user/logout">Logout</a>
</div>
{% csrf_token %}
<div class="main">
    <h1>
        Time slots
    </h1>
    <br>
    <label for="id_date">Choose date:</label>
    <input type="text" id="id_date" class="date" value="{{ date1 }}" style="width:20%">
    <br><br>
    <div class="container">
        <div class="row"> 
            <table class="table table-hover table-responsive" style="width:90%" id="myTable">
                <thead>
                    <tr>
                        <th>Start Time</th>
                        <th>End Time</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                {% for i in time %}
                    <tr>
                        <td id="f1">{{ i.int_time|time:"H:i" }}</td>
                        <td id="l1">{{ i.end_time|time:"H:i" }}</td>
                        <td><a href="/book/edit/slot/{{ i.pk }}"><button type="button" data-toggle="modal" data-target="#edit" data-uid="1" class="update btn btn-warning btn-sm"><span class="glyphicon glyphicon-pencil"></span></button></a></td>
                        <td><a href="/book/cancle/{{ i.pk }}"><button type="button" data-toggle="modal" data-target="#delete" data-uid="1" class="delete btn btn-danger btn-sm"><span class="glyphicon glyphicon-trash"></span></button></a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <h3>Please Note: The changes will be applied form {{ date2 }}</h3>
        {% if y %}
            <h3>You can only make changes while you are on current date you can only view once you change the date</h3>
        {% else %}
            <h3>Time slot can only be modified once a day</h3>
        {% endif %}
    </div>
</div>