roombooking/book/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'book'
urlpatterns = [
    path('new/slot', slot, name="slot"),
    path('',home,name="home"),
    path('new/booking',book,name="book"),
    path('<int:id>', views.cancle,name='cancle'),
    path('edit/<int:id>',views.edit),
    path('edit/slots',views.desc),
    path('edit/slot/<int:id>',views.edits),
    path('ajax',views.ajax),
    path('ajax/slot',views.ajaxs),
    path('cancle/<int:id>',views.cancles),
    path('api',views.slot_api),
    path('new/room',views.add_room),
    path('change',views.change_days),
]

roombooking/login/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LoginView,LogoutView

app_name = 'login'
urlpatterns = [
    path('sign_up',sign_up , name="sign_up"),
    path('login', LoginView.as_view(template_name='login/login.html'), name="login"),
    path('logout',LogoutView.as_view(),name="logout"),
]

roombooking/roombooking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('login.urls')),
    path('book/', include('book.urls')),
]

roombooking/login/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    is_manager=models.BooleanField(default=False)

roombooking/login/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import *

TRUE_FALSE_CHOICES = (
    (True, 'Room manager'),
    (False, 'Customer')
)

class RegistrationForm(UserCreationForm):
    is_manager=forms.ChoiceField(choices = TRUE_FALSE_CHOICES)
    class Meta:
        model = User
        fields = (
            'username',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.is_manager = self.cleaned_data['is_manager']

        if commit:
            user.save()

        return user

roombooking/login/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from django.contrib import messages
import datetime
from django.contrib.auth import logout
from django.contrib import messages
from .forms import *
import json
from django.views.decorators.csrf import csrf_exempt
def sign_up(request):
    if request.method=="POST":
        form=RegistrationForm(request.POST)
        print(bool(form.is_valid))
        # print(form.cleaned_data['password1'])
        # print(form.cleaned_data['username'])
        # print(bool(form.cleaned_data['is_manager']))
        if form.is_valid():
            form.save()
            print('Naman')
            print(form.cleaned_data['username'])
            messages.success(request,'Account created')
            return redirect('/user/login')
        else:
            return redirect('/user/sign_up')
    else:
        form=RegistrationForm()
        context={'form':form}
        return render(request,'login/sign_up.html',context)

roombooking/login/templates/login/login.html
{% load static %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'login/sign_in.css' %}">
</head>
<body>

<h2>Login Form</h2>

<form method="post">
    {% csrf_token %}
  <div class="imgcontainer">
    <img src="{% static 'login/WhatsApp Image 2020-03-09 at 19.43.09.jpeg' %}" alt="Avatar" class="avatar">
  </div>

  <div class="container">
    <label for="id_username">Username:</label>
    <input type="text" name="username" id="id_username" autofocus required>

    <label for="id_password">Password:</label>
    <input type="password" name="password" id="id_password" required>
        
    <div class="clearfix" style="display: inline-block;">
      <button type="submit" class="signupbtn" style="height: 60px;width: 100px;font-size: 25px;">Login</button>
      <a href="/user/sign_up"><button type="button" class="cancelbtn" style="height: 40px;">Not a user</button></a>
    </div>
  </div>

</form>

</body>
</html>
<!-- <html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body, html {
  height: 100%;
  font-family: Arial, Helvetica, sans-serif;
}

* {
  box-sizing: border-box;
}

.bg-img {
  /* The image used */
  background-image: url("{% static 'login/WhatsApp Image 2020-03-09 at 19.43.09.jpeg' %}");

  min-height: 380px;

  /* Center and scale the image nicely */
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;
}

/* Add styles to the form container */
.container {
  position: absolute;
  right: 0;
  margin: 20px;
  max-width: 300px;
  padding: 16px;
  background-color: white;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Set a style for the submit button */
.btn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

.btn:hover {
  opacity: 1;
}
</style>
</head>
<body>

<h2>Form on Hero Image</h2>
<div class="bg-img">
  <form action="/action_page.php" class="container">
    <h1>Login</h1>
    <label for="id_username">Username:</label>
    <input type="text" name="username" id="id_username" autofocus required>

    <label for="id_password">Password:</label>
    <input type="password" name="password" id="id_password" required>
    <button type="submit" class="btn">Login</button>
  </form>
</div>
</body>
</html> -->

roombooking/login/templates/login/sign_up.html
{% load static %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'login/signup.css' %}">
</head>

<body>

<form method="post" style="border:1px solid #ccc">
    {% csrf_token %}
  <div class="container">
    <h1>Sign Up</h1>
    <p>Please fill in this form to create an account.</p>
    <hr>
    <label for="id_is_manager">Category:</label>&nbsp;&nbsp;
    <select name="is_manager" id="id_is_manager">
    <option value="True">Room Manager</option>
    <option value="False">Faculty</option>
    </select>
    <br><br>
    <label for="id_username">Username:</label> 
    <input type="text" name="username" maxlength="150" id="id_username" autofocus required>
    <label for="id_password1">Password:</label>
    <input type="password" name="password1" id="id_password1" required> 
    <label for="id_password2">Password confirmation:</label> 
    <input type="password" name="password2" id="id_password2" required>
    
    <div class="clearfix">
      <button type="submit" class="signupbtn">Sign Up</button>
      <a href="/user/login"><button type="button" class="cancelbtn">Already a User</button></a>
    </div>
  </div>
</form>

</body>
</html>